import { defineConfig } from "drizzle-kit";

try {
  process.loadEnvFile(".env.local");
} catch {
  // .env.local is optional (e.g. CI provides DATABASE_URL directly)
}

export default defineConfig({
  // auth-schema.ts is generated by the Better Auth CLI; events.ownerId
  // references its user table, so both files must be in scope.
  schema: ["./src/db/schema.ts", "./src/db/auth-schema.ts"],
  out: "./drizzle",
  dialect: "postgresql",
  dbCredentials: { url: process.env.DATABASE_URL! },
});
